### ISSUE TITLE
Job Board Limits

### ISSUE THREAD

**Issue by bradsk88** [bradsk88/Questown#119]
### Reason to Exist
???

### Tasks
- [ ] Add ability to set desired quantity of resource
  - UI with number selector: 
     - At zero: "Villagers will produce this item whenever possible"
     - At one or more
       - With "forever" unchecked: "This request will be removed once there are N <item> in your village"
       - With "forever" checked: "Whenever your village has less than N <item>, villagers will work to produce more"
- [ ] Add ability to set "how many poeple can do this job?" (e.g. Probably only want one person exploring)
  - Later: Allow/Exclude specific people on free-for-all jobs
- [x] Add ability to reject quest batch (new batch added in the morning)
