### ISSUE TITLE
Play Testing Feedback

### ISSUE THREAD

**Issue by bradsk88** [bradsk88/Questown#90]
- [ ] [Need a journal entry for town doors](https://github.com/bradsk88/Questown/issues/121)
- [ ] [Add a quest for town gate](https://github.com/bradsk88/Questown/issues/121)
- [x] ~Bug: Storage room not working after resize?~
  - [x] MAKE IT MORE OBVIOUS THAT ALL ROOMS NEED TORCHES (did this via light_sources tag)
- [x] Villagers coming home with no loot
- [x] Support windows
- [x] Villagers should avoid water (prefer walking on "docks")
- [x] Bug: Villagers bump into each other when multiple go thru the gate
- [ ] [Villager respawns by gate if you return to village in morning, they should respawn in a room](https://github.com/bradsk88/Questown/issues/120)
- [x] Duplicate quests get achieved when you return and village rooms are re-computed
- [x] Villagers should heal in the morning
- [x] Should drop tools if they die

**Comment by bradsk88** [comment]
- [ ] [Adding more torches causes a forge to become a workshop](https://github.com/bradsk88/Questown/issues/122)
- [x] Rooms that start out small with an opening to a bigger space are not detected
- [x] Gatherers don't bring back loot?!
- [ ] [Detect interior items higher than two blocks](https://github.com/bradsk88/Questown/issues/123)
- [x] Add instrumentation to ticks and getTarget to identify slowness
